# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Kochbuch_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1441, 555)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.edit_database_path = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_database_path.setObjectName("edit_database_path")
        self.verticalLayout.addWidget(self.edit_database_path)
        self.button_load_data = QtWidgets.QPushButton(self.centralwidget)
        self.button_load_data.setObjectName("button_load_data")
        self.verticalLayout.addWidget(self.button_load_data)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_add = QtWidgets.QPushButton(self.centralwidget)
        self.button_add.setObjectName("button_add")
        self.horizontalLayout.addWidget(self.button_add)
        self.button_save = QtWidgets.QPushButton(self.centralwidget)
        self.button_save.setObjectName("button_save")
        self.horizontalLayout.addWidget(self.button_save)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.content_table = QtWidgets.QTableWidget(self.centralwidget)
        self.content_table.setObjectName("content_table")
        self.content_table.setColumnCount(9)
        self.content_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.content_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.content_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.content_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.content_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.content_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.content_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.content_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.content_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.content_table.setHorizontalHeaderItem(8, item)
        self.verticalLayout.addWidget(self.content_table)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1441, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_load_data.setText(_translate("MainWindow", "Lade Datenbank"))
        self.button_add.setText(_translate("MainWindow", "Hinzufügen"))
        self.button_save.setText(_translate("MainWindow", "Kochbuch Speichern"))
        item = self.content_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.content_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Fisch"))
        item = self.content_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Nudeln"))
        item = self.content_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Vortag"))
        item = self.content_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "SE"))
        item = self.content_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "WE"))
        item = self.content_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "WE Wichtung"))
        item = self.content_table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Wichtung"))
